// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mrm/ent/meeting"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Meeting is the model entity for the Meeting schema.
type Meeting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Applicant holds the value of the "applicant" field.
	Applicant string `json:"applicant,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MeetingQuery when eager-loading is set.
	Edges        MeetingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MeetingEdges holds the relations/edges for other nodes in the graph.
type MeetingEdges struct {
	// Mdrs holds the value of the mdrs edge.
	Mdrs []*MeetingDateRoom `json:"mdrs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MdrsOrErr returns the Mdrs value or an error if the edge
// was not loaded in eager-loading.
func (e MeetingEdges) MdrsOrErr() ([]*MeetingDateRoom, error) {
	if e.loadedTypes[0] {
		return e.Mdrs, nil
	}
	return nil, &NotLoadedError{edge: "mdrs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Meeting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case meeting.FieldID:
			values[i] = new(sql.NullInt64)
		case meeting.FieldName, meeting.FieldApplicant:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Meeting fields.
func (m *Meeting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case meeting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case meeting.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				m.Name = value.String
			}
		case meeting.FieldApplicant:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field applicant", values[i])
			} else if value.Valid {
				m.Applicant = value.String
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Meeting.
// This includes values selected through modifiers, order, etc.
func (m *Meeting) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryMdrs queries the "mdrs" edge of the Meeting entity.
func (m *Meeting) QueryMdrs() *MeetingDateRoomQuery {
	return NewMeetingClient(m.config).QueryMdrs(m)
}

// Update returns a builder for updating this Meeting.
// Note that you need to call Meeting.Unwrap() before calling this method if this Meeting
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Meeting) Update() *MeetingUpdateOne {
	return NewMeetingClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Meeting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Meeting) Unwrap() *Meeting {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Meeting is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Meeting) String() string {
	var builder strings.Builder
	builder.WriteString("Meeting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("name=")
	builder.WriteString(m.Name)
	builder.WriteString(", ")
	builder.WriteString("applicant=")
	builder.WriteString(m.Applicant)
	builder.WriteByte(')')
	return builder.String()
}

// Meetings is a parsable slice of Meeting.
type Meetings []*Meeting
