// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Meeting is the predicate function for meeting builders.
type Meeting func(*sql.Selector)

// MeetingDateRoom is the predicate function for meetingdateroom builders.
type MeetingDateRoom func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
